version: "3.8"

services:
  web:
    image: palondomus/blustoryvideoconverter:local
    container_name: blustoryvideoconverterlocal
    build:
      context: .
    ports:
      - "8080:8080"
    stdin_open: true   # equivalent to -it
    tty: true          # equivalent to -it
    restart: unless-stopped
